CREATE TABLE TB_Role
(
 CISLOROLE INT IDENTITY(1,1) NOT NULL,
 CONSTRAINT FK_CISLOROLE FOREIGN KEY (CISLOROLE)
 REFERENCES TB_UserData (ID),
 NAZEVROLE NVARCHAR(20) NOT NULL,
);

CREATE TABLE TB_UserData
(
 ID INT IDENTITY(1,1) NOT NULL,
 CONSTRAINT PK_CISLOROLE PRIMARY KEY (ID),
 USERNAME NVARCHAR(64) NOT NULL,
 USERPASSWORD VARCHAR(128) NOT NULL,
 CONSTRAINT FK_USERDATA FOREIGN KEY (ID)
 REFERENCES TB_UserProfile (ID),
);

CREATE TABLE TB_UserProfile
(
 ID INT IDENTITY(1,1) NOT NULL,
 CONSTRAINT PK_USERPROFILE PRIMARY KEY (ID),
 DESCRIPTION NVARCHAR(128),
 --USERNAME NVARCHAR(64) NOT NULL,
 --PASSWORD VARCHAR(512) NULL,
 CONSTRAINT FK_USERPROFILE FOREIGN KEY (ID)
 REFERENCES TB_Playlist (ID),
);

CREATE TABLE TB_Playlist
(
 ID INT IDENTITY(1,1) NOT NULL,
 CONTRAINT PK_PLAYLIST PRIMARY KEY (ID),
 NAME NVARCHAR(64) NOT NULL,
 PLAY_COUNT INT NULL,
 USER_PROFILE_ID INT NOT NULL,
 CONSTRAINT FK_PLAYLIST_USERPROFILE FOREIGN KEY (USER_PROFILE_ID) 
 --CONSTRAINT FK_PLAYLIST_USERPROFILE FOREIGN KEY (ID)
 REFERENCES TB_UserProfile (ID)
);

